#!/bin/bash

echo "🎯 SLA Service - API Configuration Demo"
echo "======================================="
echo ""

echo "✅ Tính năng API Configuration đã được thêm:"
echo "• Button 'API Config' trong header workflows"
echo "• Modal cấu hình API với các trường:"
echo "  - Enable API Sync (checkbox)"
echo "  - API Base URL (text input)"
echo "  - API Key (password input)"
echo "  - API Endpoints preview"
echo "• Test Connection button"
echo "• Save configuration to localStorage"
echo "• Sync Now button khi API được enable"
echo ""

echo "🎯 Cách sử dụng API Configuration:"
echo "1. Truy cập http://localhost:3001/workflows"
echo "2. Click button 'API Config' (⚙️) trong header"
echo "3. Cấu hình các thông tin:"
echo "   • Bật 'Enable API Sync'"
echo "   • Nhập 'API Base URL' (ví dụ: https://your-odoo.com)"
echo "   • Nhập 'API Key'"
echo "4. Click 'Test Connection' để kiểm tra kết nối"
echo "5. Click 'Save' để lưu cấu hình"
echo "6. Click 'Sync Now' để đồng bộ workflows từ API"
echo ""

echo "🔧 Chi tiết kỹ thuật:"
echo "• State management: apiConfig, showApiConfig, syncLoading"
echo "• localStorage để lưu cấu hình API"
echo "• Fetch API với Bearer token authentication"
echo "• Error handling và user feedback"
echo "• Conditional rendering cho Sync button"
echo "• Loading states với spinner animation"
echo ""

echo "📡 API Endpoints được hỗ trợ:"
echo "• GET {baseUrl}/api/workflows - Lấy danh sách workflows"
echo "• GET {baseUrl}/api/test - Kiểm tra kết nối API"
echo "• Headers: Authorization: Bearer {apiKey}"
echo "• Content-Type: application/json"
echo ""

echo "🎨 UI Features:"
echo "• Modal overlay với backdrop"
echo "• Form validation và error handling"
echo "• Password field cho API Key"
echo "• Endpoints preview với dynamic URL"
echo "• Loading spinner cho sync operation"
echo "• Success/error alerts"
echo ""

echo "🔄 Workflow Sync Process:"
echo "1. Enable API Sync → Sync button xuất hiện"
echo "2. Configure URL & Key → Save configuration"
echo "3. Test Connection → Verify API accessibility"
echo "4. Sync Now → Fetch workflows từ external API"
echo "5. Update UI → Display synced workflows"
echo ""

echo "💾 Data Persistence:"
echo "• API config được lưu trong localStorage"
echo "• Tự động load config khi reload trang"
echo "• Fallback về mock data nếu API disabled"
echo ""

echo "🎉 Tính năng API Configuration đã hoạt động!"
echo "Truy cập: http://localhost:3001/workflows"
