import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateAuthTables1768501827743 implements MigrationInterface {
    name = 'CreateAuthTables1768501827743'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."idx_sla_action_logs_record_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sla_action_logs_activity_id"`);
        await queryRunner.query(`CREATE TABLE "roles" ("code" character varying NOT NULL, "name" character varying NOT NULL, "permissions" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_f6d54f95c31b73fb1bdd8e91d0c" PRIMARY KEY ("code"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "username" character varying NOT NULL, "email" character varying NOT NULL, "password_hash" character varying, "full_name" character varying NOT NULL, "role_code" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "is_locked" boolean NOT NULL DEFAULT false, "auth_source" character varying NOT NULL DEFAULT 'local', "last_login_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" integer NOT NULL, "token_hash" character varying NOT NULL, "expires_at" TIMESTAMP NOT NULL, "is_revoked" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "login_history" ("id" SERIAL NOT NULL, "user_id" integer, "username" character varying NOT NULL, "ip_address" character varying, "user_agent" character varying, "status" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fe377f36d49c39547cb6b9f0727" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "enabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "workflows_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "violations_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "color" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "icon" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "api_method" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "systems" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "systems" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "systems" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transitions" ALTER COLUMN "activity_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transitions" ALTER COLUMN "sequence" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transitions" ALTER COLUMN "group_required" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transitions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transitions" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transitions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transitions" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "workflow_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "flow_start" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "flow_stop" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "flow_cancel" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "flow_done" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "violation_action" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "sla_hours" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "max_violations" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "system_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "steps" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "violations" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "on_create" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "share" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "activity_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "workflows" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflows" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "workflows" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "records" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "records" ALTER COLUMN "violation_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "records" ALTER COLUMN "sla_hours" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "records" ALTER COLUMN "remaining_hours" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "records" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "records" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "records" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "records" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sla_action_logs" ALTER COLUMN "violation_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sla_action_logs" ALTER COLUMN "is_success" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sla_action_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sla_action_logs" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sla_action_logs" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sla_action_logs" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_6bd600fd542fb1b281c17beb06" ON "transitions" ("activity_id", "id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1431600c0a434d77a462a5c090" ON "activities" ("workflow_id", "id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b39bde0bb88754674179a58055" ON "workflows" ("system_id", "model") `);
        await queryRunner.query(`CREATE INDEX "idx_records_workflow_id" ON "records" ("workflow_id") `);
        await queryRunner.query(`CREATE INDEX "idx_records_system_id" ON "records" ("system_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_50585078fa18c0e7d947f1254b" ON "sla_action_logs" ("record_id", "action_type") `);
        await queryRunner.query(`ALTER TABLE "transitions" ADD CONSTRAINT "FK_2e5d886296716c37cb8546d2d99" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_9d84824ab1b323f1f89ba3df7ca" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_4c9cc87b3af04f8eed8bc046bc9" FOREIGN KEY ("role_code") REFERENCES "roles"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_4c9cc87b3af04f8eed8bc046bc9"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_9d84824ab1b323f1f89ba3df7ca"`);
        await queryRunner.query(`ALTER TABLE "transitions" DROP CONSTRAINT "FK_2e5d886296716c37cb8546d2d99"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50585078fa18c0e7d947f1254b"`);
        await queryRunner.query(`DROP INDEX "public"."idx_records_system_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_records_workflow_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b39bde0bb88754674179a58055"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1431600c0a434d77a462a5c090"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bd600fd542fb1b281c17beb06"`);
        await queryRunner.query(`ALTER TABLE "sla_action_logs" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sla_action_logs" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sla_action_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sla_action_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sla_action_logs" ALTER COLUMN "is_success" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sla_action_logs" ALTER COLUMN "violation_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "records" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "records" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "records" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "records" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "records" ALTER COLUMN "remaining_hours" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "records" ALTER COLUMN "sla_hours" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "records" ALTER COLUMN "violation_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "records" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "workflows" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflows" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "workflows" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "activity_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "share" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "on_create" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "violations" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "steps" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "system_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "max_violations" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "sla_hours" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "violation_action" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "flow_done" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "flow_cancel" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "flow_stop" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "flow_start" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "workflow_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transitions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transitions" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transitions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transitions" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transitions" ALTER COLUMN "group_required" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transitions" ALTER COLUMN "sequence" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transitions" ALTER COLUMN "activity_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "systems" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "systems" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "systems" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "api_method" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "icon" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "color" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "violations_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "workflows_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "systems" ALTER COLUMN "enabled" DROP NOT NULL`);
        await queryRunner.query(`DROP TABLE "login_history"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`CREATE INDEX "idx_sla_action_logs_activity_id" ON "sla_action_logs" ("activity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_sla_action_logs_record_id" ON "sla_action_logs" ("record_id") `);
    }

}
